name: Trivia
description: "From ZT."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.1
  csv: ^6.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.2.2
  shared_preferences: ^2.3.2
  gif: ^2.3.0
  provider: ^6.1.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The Flutter section where assets and other Flutter-specific configurations are defined.
flutter:
  uses-material-design: true

  # Define the assets folder and give access to all assets in the assets/gif/ folder
  assets:
    - assets/gif/
