// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkzMuL_LSUXRv04bIX9-HGR1jFpuQVz4',
    appId: '1:35636239430:web:6d9b9f1efaff5ddacb3e47',
    messagingSenderId: '35636239430',
    projectId: 'kccr-ee606',
    authDomain: 'kccr-ee606.firebaseapp.com',
    storageBucket: 'kccr-ee606.appspot.com',
    measurementId: 'G-6Z6FZ60CYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQ0G76o7qNdWhU54Tn_V7Rus4frjgPOY',
    appId: '1:35636239430:android:981e3e019fd5d377cb3e47',
    messagingSenderId: '35636239430',
    projectId: 'kccr-ee606',
    storageBucket: 'kccr-ee606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU0-5sNOwj4MuNIvo-O2X07aLC4du8go8',
    appId: '1:35636239430:ios:2e464b1033b807d8cb3e47',
    messagingSenderId: '35636239430',
    projectId: 'kccr-ee606',
    storageBucket: 'kccr-ee606.appspot.com',
    androidClientId: '35636239430-erb0iqnjt51s9ks4v115d1liga45oovh.apps.googleusercontent.com',
    iosClientId: '35636239430-jrk9gm03sib41m6fsqi970h4f3kqmj4f.apps.googleusercontent.com',
    iosBundleId: 'com.zealtown.authentication.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU0-5sNOwj4MuNIvo-O2X07aLC4du8go8',
    appId: '1:35636239430:ios:2e464b1033b807d8cb3e47',
    messagingSenderId: '35636239430',
    projectId: 'kccr-ee606',
    storageBucket: 'kccr-ee606.appspot.com',
    androidClientId: '35636239430-erb0iqnjt51s9ks4v115d1liga45oovh.apps.googleusercontent.com',
    iosClientId: '35636239430-jrk9gm03sib41m6fsqi970h4f3kqmj4f.apps.googleusercontent.com',
    iosBundleId: 'com.zealtown.authentication.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkzMuL_LSUXRv04bIX9-HGR1jFpuQVz4',
    appId: '1:35636239430:web:2d53a828abebcbb6cb3e47',
    messagingSenderId: '35636239430',
    projectId: 'kccr-ee606',
    authDomain: 'kccr-ee606.firebaseapp.com',
    storageBucket: 'kccr-ee606.appspot.com',
    measurementId: 'G-SH33M9SFRN',
  );
}
